name: Configuration Update Base
type: module
description: 'Provides basic revert and update functionality for other modules'
core: 8.x
core_version_requirement: ^8 || ^9 || ^10
dependencies:
  - drupal:config

# Information added by Drupal.org packaging script on 2020-04-08
version: '8.x-1.7'
project: 'config_update'
datestamp: 1586355588
