version: '3.0'

# Mount for easier dev
x-volumes: &default-volumes
  volumes:
    - ./modules:/app/web/modules/custom:${VOLUME_FLAGS:-delegated}

services:
  cli:
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.govcms
      args:
        GOVCMS_PROJECT_VERSION: ${GOVCMS_PROJECT_VERSION:-2.x-dev}
        LAGOON_IMAGE_VERSION: ${LAGOON_IMAGE_VERSION:-latest}
        COMPOSER_AUTH: ${COMPOSER_AUTH:-}
        GITHUB_TOKEN: ${GITHUB_TOKEN:-}
    image: ${DOCKERHUB_NAMESPACE:-govcms}/${GOVCMS_CLI_IMAGE_NAME:-govcms}:${GOVCMS_RELEASE_TAG:-latest}
    environment:
      LAGOON_ROUTE: ${LOCALDEV_URL:-http://govcmslagoon.docker.amazee.io}
    << : *default-volumes


  test:
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.test
      args:
        CLI_IMAGE: ${DOCKERHUB_NAMESPACE:-govcms}/${GOVCMS_CLI_IMAGE_NAME:-govcms}:${GOVCMS_RELEASE_TAG:-latest}
        LAGOON_IMAGE_VERSION: ${LAGOON_IMAGE_VERSION:-latest}
        COMPOSER_AUTH: ${COMPOSER_AUTH:-}
    image: ${DOCKERHUB_NAMESPACE:-govcms}/test:${GOVCMS_RELEASE_TAG:-latest}
    depends_on:
      - cli

  nginx:
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.nginx-drupal
      args:
        CLI_IMAGE: ${DOCKERHUB_NAMESPACE:-govcms}/${GOVCMS_CLI_IMAGE_NAME:-govcms}:${GOVCMS_RELEASE_TAG:-latest}
        LAGOON_IMAGE_VERSION: ${LAGOON_IMAGE_VERSION:-latest}
    image: ${DOCKERHUB_NAMESPACE:-govcms}/nginx-drupal:${GOVCMS_RELEASE_TAG:-latest}
    environment:
      LAGOON_ROUTE: ${LOCALDEV_URL:-http://govcmslagoon.docker.amazee.io}
      LAGOON_LOCALDEV_URL: ${LOCALDEV_URL_NGINX:-http://govcms-lagoon-nginx.docker.amazee.io}
      X_FRAME_OPTIONS: ${X_FRAME_OPTIONS:-SAMEORIGIN}
    networks:
      - amazeeio-network
      - default
    << : *default-volumes


  php:
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.php
      args:
        CLI_IMAGE: ${DOCKERHUB_NAMESPACE:-govcms}/${GOVCMS_CLI_IMAGE_NAME:-govcms}:${GOVCMS_RELEASE_TAG:-latest}
        LAGOON_IMAGE_VERSION: ${LAGOON_IMAGE_VERSION:-latest}
        LAGOON_ROUTE: ${LOCALDEV_URL:-http://govcmslagoon.docker.amazee.io}
    image: ${DOCKERHUB_NAMESPACE:-govcms}/php:${GOVCMS_RELEASE_TAG:-latest}
    << : *default-volumes


  mariadb:
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.mariadb-drupal
      args:
        LAGOON_IMAGE_VERSION: ${LAGOON_IMAGE_VERSION:-latest}
    image: ${DOCKERHUB_NAMESPACE:-govcms}/mariadb-drupal:${GOVCMS_RELEASE_TAG:-latest}
    ports:
      - "3306" # Find port on host with `docker-compose port mariadb 3306`

  redis:
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.redis
      args:
        LAGOON_IMAGE_VERSION: ${LAGOON_IMAGE_VERSION:-latest}
        LAGOON_ROUTE: ${LOCALDEV_URL:-http://govcmslagoon.docker.amazee.io}
    image: ${DOCKERHUB_NAMESPACE:-govcms}/redis:${GOVCMS_RELEASE_TAG:-latest}

  solr:
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.solr
      args:
        CLI_IMAGE: ${DOCKERHUB_NAMESPACE:-govcms}/${GOVCMS_CLI_IMAGE_NAME:-govcms}:${GOVCMS_RELEASE_TAG:-latest}
        LAGOON_IMAGE_VERSION: ${LAGOON_IMAGE_VERSION:-latest}
    image: ${DOCKERHUB_NAMESPACE:-govcms}/solr:${GOVCMS_RELEASE_TAG:-latest}
    ports:
      - "8983" # Find port on host with `docker-compose port solr 8983`

  varnish:
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.varnish-drupal
      args:
        LAGOON_IMAGE_VERSION: ${LAGOON_IMAGE_VERSION:-latest}
    image: ${DOCKERHUB_NAMESPACE:-govcms}/varnish-drupal:${GOVCMS_RELEASE_TAG:-latest}
    environment:
      VARNISH_BYPASS: "true"
    networks:
      - amazeeio-network
      - default

  chrome:
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.chrome
    image: selenium/standalone-chrome
    shm_size: '1gb'
    depends_on:
      - test

networks:
  amazeeio-network:
    external: true
  default:
    external: false
