version: '2.3'

x-volumes:
  &default-volumes
    volumes:
      - files:/app/web/sites/default/files

x-environment:
  &default-environment
    LAGOON_ROUTE: ${LOCALDEV_URL:-http://govcms8lagoon.docker.amazee.io}
    DEV_MODE: ${DEV_MODE:-false}
    CACHE_MAX_AGE: ${CACHE_MAX_AGE:-3600}

volumes:
  files: {}

services:

  cli:
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.govcms8
      args:
        GOVCMS_PROJECT_VERSION: ${GOVCMS_PROJECT_VERSION:-^1.0}
        DRUPAL_CORE_VERSION: ${DRUPAL_CORE_VERSION:-^8.8}
        LAGOON_IMAGE_VERSION: ${LAGOON_IMAGE_VERSION:-latest}
        PHP_IMAGE_VERSION: ${PHP_IMAGE_VERSION:-7.4}
        COMPOSER_AUTH: ${COMPOSER_AUTH:-}
        GITHUB_TOKEN: ${GITHUB_TOKEN:-}
    image: ${DOCKERHUB_NAMESPACE:-govcms8lagoon}/govcms8
    << : *default-volumes
    environment:
      << : *default-environment

  test:
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.test
      args:
        CLI_IMAGE: ${DOCKERHUB_NAMESPACE:-govcms8lagoon}/govcms8
        LAGOON_IMAGE_VERSION: ${LAGOON_IMAGE_VERSION:-latest}
        PHP_IMAGE_VERSION: ${PHP_IMAGE_VERSION:-7.4}
        SITE_AUDIT_VERSION: ${SITE_AUDIT_VERSION:-7.x-3.x}
        COMPOSER_AUTH: ${COMPOSER_AUTH:-}
    image: ${DOCKERHUB_NAMESPACE:-govcms8lagoon}/test
    << : *default-volumes
    depends_on:
      - cli
    environment:
      << : *default-environment

  nginx:
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.nginx-drupal
      args:
        CLI_IMAGE: ${DOCKERHUB_NAMESPACE:-govcms8lagoon}/govcms8
        LAGOON_IMAGE_VERSION: ${LAGOON_IMAGE_VERSION:-latest}
    image: ${DOCKERHUB_NAMESPACE:-govcms8lagoon}/nginx-drupal
    << : *default-volumes
    environment:
      << : *default-environment
      LAGOON_LOCALDEV_URL: ${LOCALDEV_URL_NGINX:-http://govcms8-lagoon-nginx.docker.amazee.io}
      X_FRAME_OPTIONS: ${X_FRAME_OPTIONS:-SameOrigin}
    networks:
      - amazeeio-network
      - default

  php:
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.php
      args:
        CLI_IMAGE: ${DOCKERHUB_NAMESPACE:-govcms8lagoon}/govcms8
        LAGOON_IMAGE_VERSION: ${LAGOON_IMAGE_VERSION:-latest}
        PHP_IMAGE_VERSION: ${PHP_IMAGE_VERSION:-7.4}
    image: ${DOCKERHUB_NAMESPACE:-govcms8lagoon}/php
    << : *default-volumes
    environment:
      << : *default-environment

  mariadb:
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.mariadb-drupal
      args:
        LAGOON_IMAGE_VERSION: ${LAGOON_IMAGE_VERSION:-latest}
    image: ${DOCKERHUB_NAMESPACE:-govcms8lagoon}/mariadb-drupal
    ports:
      - "3306" # Find port on host with `docker-compose port mariadb 3306`
    environment:
      << : *default-environment

  redis:
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.redis
      args:
        LAGOON_IMAGE_VERSION: ${LAGOON_IMAGE_VERSION:-latest}
    image: ${DOCKERHUB_NAMESPACE:-govcms8lagoon}/redis
    environment:
      << : *default-environment

  solr:
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.solr
      args:
        CLI_IMAGE: ${DOCKERHUB_NAMESPACE:-govcms8lagoon}/govcms8
    image: ${DOCKERHUB_NAMESPACE:-govcms8lagoon}/solr
    ports:
      - "8983" # Find port on host with `docker-compose port solr 8983`
    environment:
      << : *default-environment

  varnish:
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.varnish-drupal
      args:
        LAGOON_IMAGE_VERSION: ${LAGOON_IMAGE_VERSION:-latest}
    image: ${DOCKERHUB_NAMESPACE:-govcms8lagoon}/varnish-drupal
    environment:
      << : *default-environment
      VARNISH_BYPASS: "true"
    networks:
      - amazeeio-network
      - default

  chrome:
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.chrome
    image: selenium/standalone-chrome
    shm_size: '1gb'
    depends_on:
      - test
    << : *default-volumes

networks:
  amazeeio-network:
    external: true
