encrypt.settings:
  type: config_object
  label: 'Encrypt Settings'
  mapping:
    check_profile_status:
      type: boolean
      label: 'Check profile validation status.'
    allow_deprecated_plugins:
      type: boolean
      label: 'Deprecated encryption plugins allowed.'
