version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: quay.io/govcms/govcms-ci
        environment:
          COMPOSER_ALLOW_SUPERUSER: 1
          COMPOSE_PROJECT_NAME: govcms8lagoon
    steps:
      - checkout
      - run:
          name: Docker-compose validate
          command: docker-compose config -q
      - run:
          name: Update codebase to follow CI configuration
          command: |
            cp .env.default .env
      - setup_remote_docker
      - run:
          name: Start amazeeio-network
          command: docker network prune -f && docker network inspect amazeeio-network >/dev/null || docker network create amazeeio-network
      - run:
          name: Build project
          command: |
            docker-compose up -d --build
            docker-compose exec test dockerize -wait tcp://mariadb:3306 -timeout 1m
      - run:
          name: Run tests for containers
          command: ./tests/goss/run_all.sh
      - run:
          name: Install site
          command: docker-compose exec -T test drush si -y govcms -- install_configure_form.update_status_module='array(FALSE,FALSE)'
      - run:
          name: Get site and module version status
          command: |
            docker-compose exec -T test php -v
            docker-compose exec -T test drush st
            docker-compose exec -T test drush pml
      - run:
          name: Test that Redis is functional
          command: |
            # Set ENABLE_REDIS env var and warm cache with a bootstrap
            docker-compose exec -T --env ENABLE_REDIS=true cli drush status
            redisKeys=$(docker-compose exec -T redis redis-cli KEYS '*' | wc -l)
            if [[ $redisKeys -le 1 ]]; then
              echo 'Redis fail: No valid cache keys.'
              exit 1
            else
              echo "Redis success: Redis contains $redisKeys keys."
            fi
      - run:
          name: Test Nginx configuration
          command: |
            docker-compose exec nginx nginx -t
            composer install -d .docker/images/nginx/tests
            .docker/images/nginx/tests/vendor/bin/phpunit -c .docker/images/nginx/tests/phpunit.xml

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
