name: Custom Permissions
type: module
description: Allows additional permissions to be created and managed through an administration form.
core: 8.x
core_version_requirement: ^8 || ^9 || ^10
configure: custom_perms_select_list_form
package: Permissions
features: true

# Information added by Drupal.org packaging script on 2020-06-05
version: '8.x-2.0'
project: 'config_perms'
datestamp: 1591397579
